import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.scss";
import "@/styles/styles.scss";
import Footer from "@/components/globals/Footer";
import Navbar from "@/components/globals/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <header>
          <Navbar />
        </header>

        <main>
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
        
      </body>
    </html>
  );
}
